services:
  - type: web
    name: bot-cobranca-whatsapp
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: BOT_SUPABASE_URL
        sync: false
      - key: BOT_SUPABASE_KEY
        sync: false
      - key: HORA_ENVIO_LEMBRETES
        value: "09:00"
      - key: HORA_ENVIO_VENCIMENTO
        value: "09:00"
      - key: HORA_ENVIO_ATRASO
        value: "10:00"

